// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package asyncv1beta1

import (
	abci "cosmossdk.io/api/tendermint/abci"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_AsyncInjectedTx_1_list)(nil)

type _AsyncInjectedTx_1_list struct {
	list *[]*FutureResult
}

func (x *_AsyncInjectedTx_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_AsyncInjectedTx_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_AsyncInjectedTx_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*FutureResult)
	(*x.list)[i] = concreteValue
}

func (x *_AsyncInjectedTx_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*FutureResult)
	*x.list = append(*x.list, concreteValue)
}

func (x *_AsyncInjectedTx_1_list) AppendMutable() protoreflect.Value {
	v := new(FutureResult)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_AsyncInjectedTx_1_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_AsyncInjectedTx_1_list) NewElement() protoreflect.Value {
	v := new(FutureResult)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_AsyncInjectedTx_1_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_AsyncInjectedTx_2_list)(nil)

type _AsyncInjectedTx_2_list struct {
	list *[]*abci.ExtendedVoteInfo
}

func (x *_AsyncInjectedTx_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_AsyncInjectedTx_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_AsyncInjectedTx_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*abci.ExtendedVoteInfo)
	(*x.list)[i] = concreteValue
}

func (x *_AsyncInjectedTx_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*abci.ExtendedVoteInfo)
	*x.list = append(*x.list, concreteValue)
}

func (x *_AsyncInjectedTx_2_list) AppendMutable() protoreflect.Value {
	v := new(abci.ExtendedVoteInfo)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_AsyncInjectedTx_2_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_AsyncInjectedTx_2_list) NewElement() protoreflect.Value {
	v := new(abci.ExtendedVoteInfo)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_AsyncInjectedTx_2_list) IsValid() bool {
	return x.list != nil
}

var (
	md_AsyncInjectedTx                     protoreflect.MessageDescriptor
	fd_AsyncInjectedTx_results             protoreflect.FieldDescriptor
	fd_AsyncInjectedTx_extended_votes_info protoreflect.FieldDescriptor
)

func init() {
	file_warden_async_v1beta1_ve_proto_init()
	md_AsyncInjectedTx = File_warden_async_v1beta1_ve_proto.Messages().ByName("AsyncInjectedTx")
	fd_AsyncInjectedTx_results = md_AsyncInjectedTx.Fields().ByName("results")
	fd_AsyncInjectedTx_extended_votes_info = md_AsyncInjectedTx.Fields().ByName("extended_votes_info")
}

var _ protoreflect.Message = (*fastReflection_AsyncInjectedTx)(nil)

type fastReflection_AsyncInjectedTx AsyncInjectedTx

func (x *AsyncInjectedTx) ProtoReflect() protoreflect.Message {
	return (*fastReflection_AsyncInjectedTx)(x)
}

func (x *AsyncInjectedTx) slowProtoReflect() protoreflect.Message {
	mi := &file_warden_async_v1beta1_ve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_AsyncInjectedTx_messageType fastReflection_AsyncInjectedTx_messageType
var _ protoreflect.MessageType = fastReflection_AsyncInjectedTx_messageType{}

type fastReflection_AsyncInjectedTx_messageType struct{}

func (x fastReflection_AsyncInjectedTx_messageType) Zero() protoreflect.Message {
	return (*fastReflection_AsyncInjectedTx)(nil)
}
func (x fastReflection_AsyncInjectedTx_messageType) New() protoreflect.Message {
	return new(fastReflection_AsyncInjectedTx)
}
func (x fastReflection_AsyncInjectedTx_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_AsyncInjectedTx
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_AsyncInjectedTx) Descriptor() protoreflect.MessageDescriptor {
	return md_AsyncInjectedTx
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_AsyncInjectedTx) Type() protoreflect.MessageType {
	return _fastReflection_AsyncInjectedTx_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_AsyncInjectedTx) New() protoreflect.Message {
	return new(fastReflection_AsyncInjectedTx)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_AsyncInjectedTx) Interface() protoreflect.ProtoMessage {
	return (*AsyncInjectedTx)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_AsyncInjectedTx) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.Results) != 0 {
		value := protoreflect.ValueOfList(&_AsyncInjectedTx_1_list{list: &x.Results})
		if !f(fd_AsyncInjectedTx_results, value) {
			return
		}
	}
	if len(x.ExtendedVotesInfo) != 0 {
		value := protoreflect.ValueOfList(&_AsyncInjectedTx_2_list{list: &x.ExtendedVotesInfo})
		if !f(fd_AsyncInjectedTx_extended_votes_info, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_AsyncInjectedTx) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncInjectedTx.results":
		return len(x.Results) != 0
	case "warden.async.v1beta1.AsyncInjectedTx.extended_votes_info":
		return len(x.ExtendedVotesInfo) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncInjectedTx"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncInjectedTx does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncInjectedTx) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncInjectedTx.results":
		x.Results = nil
	case "warden.async.v1beta1.AsyncInjectedTx.extended_votes_info":
		x.ExtendedVotesInfo = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncInjectedTx"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncInjectedTx does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_AsyncInjectedTx) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "warden.async.v1beta1.AsyncInjectedTx.results":
		if len(x.Results) == 0 {
			return protoreflect.ValueOfList(&_AsyncInjectedTx_1_list{})
		}
		listValue := &_AsyncInjectedTx_1_list{list: &x.Results}
		return protoreflect.ValueOfList(listValue)
	case "warden.async.v1beta1.AsyncInjectedTx.extended_votes_info":
		if len(x.ExtendedVotesInfo) == 0 {
			return protoreflect.ValueOfList(&_AsyncInjectedTx_2_list{})
		}
		listValue := &_AsyncInjectedTx_2_list{list: &x.ExtendedVotesInfo}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncInjectedTx"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncInjectedTx does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncInjectedTx) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncInjectedTx.results":
		lv := value.List()
		clv := lv.(*_AsyncInjectedTx_1_list)
		x.Results = *clv.list
	case "warden.async.v1beta1.AsyncInjectedTx.extended_votes_info":
		lv := value.List()
		clv := lv.(*_AsyncInjectedTx_2_list)
		x.ExtendedVotesInfo = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncInjectedTx"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncInjectedTx does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncInjectedTx) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncInjectedTx.results":
		if x.Results == nil {
			x.Results = []*FutureResult{}
		}
		value := &_AsyncInjectedTx_1_list{list: &x.Results}
		return protoreflect.ValueOfList(value)
	case "warden.async.v1beta1.AsyncInjectedTx.extended_votes_info":
		if x.ExtendedVotesInfo == nil {
			x.ExtendedVotesInfo = []*abci.ExtendedVoteInfo{}
		}
		value := &_AsyncInjectedTx_2_list{list: &x.ExtendedVotesInfo}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncInjectedTx"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncInjectedTx does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_AsyncInjectedTx) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncInjectedTx.results":
		list := []*FutureResult{}
		return protoreflect.ValueOfList(&_AsyncInjectedTx_1_list{list: &list})
	case "warden.async.v1beta1.AsyncInjectedTx.extended_votes_info":
		list := []*abci.ExtendedVoteInfo{}
		return protoreflect.ValueOfList(&_AsyncInjectedTx_2_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncInjectedTx"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncInjectedTx does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_AsyncInjectedTx) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in warden.async.v1beta1.AsyncInjectedTx", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_AsyncInjectedTx) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncInjectedTx) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_AsyncInjectedTx) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_AsyncInjectedTx) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*AsyncInjectedTx)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.Results) > 0 {
			for _, e := range x.Results {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if len(x.ExtendedVotesInfo) > 0 {
			for _, e := range x.ExtendedVotesInfo {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*AsyncInjectedTx)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ExtendedVotesInfo) > 0 {
			for iNdEx := len(x.ExtendedVotesInfo) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.ExtendedVotesInfo[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x12
			}
		}
		if len(x.Results) > 0 {
			for iNdEx := len(x.Results) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Results[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*AsyncInjectedTx)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AsyncInjectedTx: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AsyncInjectedTx: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Results = append(x.Results, &FutureResult{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Results[len(x.Results)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ExtendedVotesInfo", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ExtendedVotesInfo = append(x.ExtendedVotesInfo, &abci.ExtendedVoteInfo{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.ExtendedVotesInfo[len(x.ExtendedVotesInfo)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var _ protoreflect.List = (*_AsyncVoteExtension_1_list)(nil)

type _AsyncVoteExtension_1_list struct {
	list *[]*AsyncVoteExtensionItem
}

func (x *_AsyncVoteExtension_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_AsyncVoteExtension_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_AsyncVoteExtension_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*AsyncVoteExtensionItem)
	(*x.list)[i] = concreteValue
}

func (x *_AsyncVoteExtension_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*AsyncVoteExtensionItem)
	*x.list = append(*x.list, concreteValue)
}

func (x *_AsyncVoteExtension_1_list) AppendMutable() protoreflect.Value {
	v := new(AsyncVoteExtensionItem)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_AsyncVoteExtension_1_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_AsyncVoteExtension_1_list) NewElement() protoreflect.Value {
	v := new(AsyncVoteExtensionItem)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_AsyncVoteExtension_1_list) IsValid() bool {
	return x.list != nil
}

var (
	md_AsyncVoteExtension       protoreflect.MessageDescriptor
	fd_AsyncVoteExtension_votes protoreflect.FieldDescriptor
)

func init() {
	file_warden_async_v1beta1_ve_proto_init()
	md_AsyncVoteExtension = File_warden_async_v1beta1_ve_proto.Messages().ByName("AsyncVoteExtension")
	fd_AsyncVoteExtension_votes = md_AsyncVoteExtension.Fields().ByName("votes")
}

var _ protoreflect.Message = (*fastReflection_AsyncVoteExtension)(nil)

type fastReflection_AsyncVoteExtension AsyncVoteExtension

func (x *AsyncVoteExtension) ProtoReflect() protoreflect.Message {
	return (*fastReflection_AsyncVoteExtension)(x)
}

func (x *AsyncVoteExtension) slowProtoReflect() protoreflect.Message {
	mi := &file_warden_async_v1beta1_ve_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_AsyncVoteExtension_messageType fastReflection_AsyncVoteExtension_messageType
var _ protoreflect.MessageType = fastReflection_AsyncVoteExtension_messageType{}

type fastReflection_AsyncVoteExtension_messageType struct{}

func (x fastReflection_AsyncVoteExtension_messageType) Zero() protoreflect.Message {
	return (*fastReflection_AsyncVoteExtension)(nil)
}
func (x fastReflection_AsyncVoteExtension_messageType) New() protoreflect.Message {
	return new(fastReflection_AsyncVoteExtension)
}
func (x fastReflection_AsyncVoteExtension_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_AsyncVoteExtension
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_AsyncVoteExtension) Descriptor() protoreflect.MessageDescriptor {
	return md_AsyncVoteExtension
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_AsyncVoteExtension) Type() protoreflect.MessageType {
	return _fastReflection_AsyncVoteExtension_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_AsyncVoteExtension) New() protoreflect.Message {
	return new(fastReflection_AsyncVoteExtension)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_AsyncVoteExtension) Interface() protoreflect.ProtoMessage {
	return (*AsyncVoteExtension)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_AsyncVoteExtension) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.Votes) != 0 {
		value := protoreflect.ValueOfList(&_AsyncVoteExtension_1_list{list: &x.Votes})
		if !f(fd_AsyncVoteExtension_votes, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_AsyncVoteExtension) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtension.votes":
		return len(x.Votes) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtension"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtension does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtension) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtension.votes":
		x.Votes = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtension"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtension does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_AsyncVoteExtension) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtension.votes":
		if len(x.Votes) == 0 {
			return protoreflect.ValueOfList(&_AsyncVoteExtension_1_list{})
		}
		listValue := &_AsyncVoteExtension_1_list{list: &x.Votes}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtension"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtension does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtension) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtension.votes":
		lv := value.List()
		clv := lv.(*_AsyncVoteExtension_1_list)
		x.Votes = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtension"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtension does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtension) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtension.votes":
		if x.Votes == nil {
			x.Votes = []*AsyncVoteExtensionItem{}
		}
		value := &_AsyncVoteExtension_1_list{list: &x.Votes}
		return protoreflect.ValueOfList(value)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtension"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtension does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_AsyncVoteExtension) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtension.votes":
		list := []*AsyncVoteExtensionItem{}
		return protoreflect.ValueOfList(&_AsyncVoteExtension_1_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtension"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtension does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_AsyncVoteExtension) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in warden.async.v1beta1.AsyncVoteExtension", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_AsyncVoteExtension) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtension) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_AsyncVoteExtension) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_AsyncVoteExtension) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*AsyncVoteExtension)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.Votes) > 0 {
			for _, e := range x.Votes {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*AsyncVoteExtension)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Votes) > 0 {
			for iNdEx := len(x.Votes) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Votes[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*AsyncVoteExtension)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AsyncVoteExtension: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AsyncVoteExtension: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Votes = append(x.Votes, &AsyncVoteExtensionItem{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Votes[len(x.Votes)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_AsyncVoteExtensionItem           protoreflect.MessageDescriptor
	fd_AsyncVoteExtensionItem_future_id protoreflect.FieldDescriptor
	fd_AsyncVoteExtensionItem_vote      protoreflect.FieldDescriptor
)

func init() {
	file_warden_async_v1beta1_ve_proto_init()
	md_AsyncVoteExtensionItem = File_warden_async_v1beta1_ve_proto.Messages().ByName("AsyncVoteExtensionItem")
	fd_AsyncVoteExtensionItem_future_id = md_AsyncVoteExtensionItem.Fields().ByName("future_id")
	fd_AsyncVoteExtensionItem_vote = md_AsyncVoteExtensionItem.Fields().ByName("vote")
}

var _ protoreflect.Message = (*fastReflection_AsyncVoteExtensionItem)(nil)

type fastReflection_AsyncVoteExtensionItem AsyncVoteExtensionItem

func (x *AsyncVoteExtensionItem) ProtoReflect() protoreflect.Message {
	return (*fastReflection_AsyncVoteExtensionItem)(x)
}

func (x *AsyncVoteExtensionItem) slowProtoReflect() protoreflect.Message {
	mi := &file_warden_async_v1beta1_ve_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_AsyncVoteExtensionItem_messageType fastReflection_AsyncVoteExtensionItem_messageType
var _ protoreflect.MessageType = fastReflection_AsyncVoteExtensionItem_messageType{}

type fastReflection_AsyncVoteExtensionItem_messageType struct{}

func (x fastReflection_AsyncVoteExtensionItem_messageType) Zero() protoreflect.Message {
	return (*fastReflection_AsyncVoteExtensionItem)(nil)
}
func (x fastReflection_AsyncVoteExtensionItem_messageType) New() protoreflect.Message {
	return new(fastReflection_AsyncVoteExtensionItem)
}
func (x fastReflection_AsyncVoteExtensionItem_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_AsyncVoteExtensionItem
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_AsyncVoteExtensionItem) Descriptor() protoreflect.MessageDescriptor {
	return md_AsyncVoteExtensionItem
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_AsyncVoteExtensionItem) Type() protoreflect.MessageType {
	return _fastReflection_AsyncVoteExtensionItem_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_AsyncVoteExtensionItem) New() protoreflect.Message {
	return new(fastReflection_AsyncVoteExtensionItem)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_AsyncVoteExtensionItem) Interface() protoreflect.ProtoMessage {
	return (*AsyncVoteExtensionItem)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_AsyncVoteExtensionItem) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.FutureId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.FutureId)
		if !f(fd_AsyncVoteExtensionItem_future_id, value) {
			return
		}
	}
	if x.Vote != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Vote))
		if !f(fd_AsyncVoteExtensionItem_vote, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_AsyncVoteExtensionItem) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtensionItem.future_id":
		return x.FutureId != uint64(0)
	case "warden.async.v1beta1.AsyncVoteExtensionItem.vote":
		return x.Vote != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtensionItem"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtensionItem does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtensionItem) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtensionItem.future_id":
		x.FutureId = uint64(0)
	case "warden.async.v1beta1.AsyncVoteExtensionItem.vote":
		x.Vote = 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtensionItem"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtensionItem does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_AsyncVoteExtensionItem) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtensionItem.future_id":
		value := x.FutureId
		return protoreflect.ValueOfUint64(value)
	case "warden.async.v1beta1.AsyncVoteExtensionItem.vote":
		value := x.Vote
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtensionItem"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtensionItem does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtensionItem) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtensionItem.future_id":
		x.FutureId = value.Uint()
	case "warden.async.v1beta1.AsyncVoteExtensionItem.vote":
		x.Vote = (FutureVoteType)(value.Enum())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtensionItem"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtensionItem does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtensionItem) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtensionItem.future_id":
		panic(fmt.Errorf("field future_id of message warden.async.v1beta1.AsyncVoteExtensionItem is not mutable"))
	case "warden.async.v1beta1.AsyncVoteExtensionItem.vote":
		panic(fmt.Errorf("field vote of message warden.async.v1beta1.AsyncVoteExtensionItem is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtensionItem"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtensionItem does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_AsyncVoteExtensionItem) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "warden.async.v1beta1.AsyncVoteExtensionItem.future_id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "warden.async.v1beta1.AsyncVoteExtensionItem.vote":
		return protoreflect.ValueOfEnum(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: warden.async.v1beta1.AsyncVoteExtensionItem"))
		}
		panic(fmt.Errorf("message warden.async.v1beta1.AsyncVoteExtensionItem does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_AsyncVoteExtensionItem) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in warden.async.v1beta1.AsyncVoteExtensionItem", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_AsyncVoteExtensionItem) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AsyncVoteExtensionItem) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_AsyncVoteExtensionItem) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_AsyncVoteExtensionItem) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*AsyncVoteExtensionItem)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.FutureId != 0 {
			n += 1 + runtime.Sov(uint64(x.FutureId))
		}
		if x.Vote != 0 {
			n += 1 + runtime.Sov(uint64(x.Vote))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*AsyncVoteExtensionItem)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Vote != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Vote))
			i--
			dAtA[i] = 0x10
		}
		if x.FutureId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.FutureId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*AsyncVoteExtensionItem)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AsyncVoteExtensionItem: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AsyncVoteExtensionItem: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FutureId", wireType)
				}
				x.FutureId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.FutureId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Vote", wireType)
				}
				x.Vote = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Vote |= FutureVoteType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: warden/async/v1beta1/ve.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsyncInjectedTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The results of the execution of the Futures.
	Results []*FutureResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// All the vote extensions gathered for this block.
	// TODO: slinky also does that, so technically we're duplicating information and wasting block space.
	ExtendedVotesInfo []*abci.ExtendedVoteInfo `protobuf:"bytes,2,rep,name=extended_votes_info,json=extendedVotesInfo,proto3" json:"extended_votes_info,omitempty"`
}

func (x *AsyncInjectedTx) Reset() {
	*x = AsyncInjectedTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warden_async_v1beta1_ve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncInjectedTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncInjectedTx) ProtoMessage() {}

// Deprecated: Use AsyncInjectedTx.ProtoReflect.Descriptor instead.
func (*AsyncInjectedTx) Descriptor() ([]byte, []int) {
	return file_warden_async_v1beta1_ve_proto_rawDescGZIP(), []int{0}
}

func (x *AsyncInjectedTx) GetResults() []*FutureResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *AsyncInjectedTx) GetExtendedVotesInfo() []*abci.ExtendedVoteInfo {
	if x != nil {
		return x.ExtendedVotesInfo
	}
	return nil
}

// A vote extension coming from a validator. It contains multiple votes for
// different Futures.
type AsyncVoteExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Votes []*AsyncVoteExtensionItem `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
}

func (x *AsyncVoteExtension) Reset() {
	*x = AsyncVoteExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warden_async_v1beta1_ve_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncVoteExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncVoteExtension) ProtoMessage() {}

// Deprecated: Use AsyncVoteExtension.ProtoReflect.Descriptor instead.
func (*AsyncVoteExtension) Descriptor() ([]byte, []int) {
	return file_warden_async_v1beta1_ve_proto_rawDescGZIP(), []int{1}
}

func (x *AsyncVoteExtension) GetVotes() []*AsyncVoteExtensionItem {
	if x != nil {
		return x.Votes
	}
	return nil
}

type AsyncVoteExtensionItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FutureId uint64         `protobuf:"varint,1,opt,name=future_id,json=futureId,proto3" json:"future_id,omitempty"`
	Vote     FutureVoteType `protobuf:"varint,2,opt,name=vote,proto3,enum=warden.async.v1beta1.FutureVoteType" json:"vote,omitempty"`
}

func (x *AsyncVoteExtensionItem) Reset() {
	*x = AsyncVoteExtensionItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_warden_async_v1beta1_ve_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncVoteExtensionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncVoteExtensionItem) ProtoMessage() {}

// Deprecated: Use AsyncVoteExtensionItem.ProtoReflect.Descriptor instead.
func (*AsyncVoteExtensionItem) Descriptor() ([]byte, []int) {
	return file_warden_async_v1beta1_ve_proto_rawDescGZIP(), []int{2}
}

func (x *AsyncVoteExtensionItem) GetFutureId() uint64 {
	if x != nil {
		return x.FutureId
	}
	return 0
}

func (x *AsyncVoteExtensionItem) GetVote() FutureVoteType {
	if x != nil {
		return x.Vote
	}
	return FutureVoteType_VOTE_TYPE_UNSPECIFIED
}

var File_warden_async_v1beta1_ve_proto protoreflect.FileDescriptor

var file_warden_async_v1beta1_ve_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2f, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2f, 0x61, 0x62, 0x63, 0x69, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x2f, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x66,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x0f,
	0x41, 0x73, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x78, 0x12,
	0x3c, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x57, 0x0a,
	0x13, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x62, 0x63, 0x69, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x65, 0x64, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x04, 0xc8,
	0xde, 0x1f, 0x00, 0x52, 0x11, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x56, 0x6f, 0x74,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x58, 0x0a, 0x12, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x56,
	0x6f, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x05,
	0x76, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x77, 0x61,
	0x72, 0x64, 0x65, 0x6e, 0x2e, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x56, 0x6f, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73,
	0x22, 0x6f, 0x0a, 0x16, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x56, 0x6f, 0x74, 0x65, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x61,
	0x73, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x46, 0x75, 0x74,
	0x75, 0x72, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x76, 0x6f, 0x74,
	0x65, 0x42, 0xe6, 0x01, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x2e, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x42, 0x07,
	0x56, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2f,
	0x61, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x3b, 0x61, 0x73,
	0x79, 0x6e, 0x63, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xa2, 0x02, 0x03, 0x57, 0x41, 0x58,
	0xaa, 0x02, 0x14, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x2e,
	0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xca, 0x02, 0x14, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x5c, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x5c, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xe2, 0x02,
	0x20, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x5c, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x5c, 0x56, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x16, 0x57, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x3a, 0x3a, 0x41, 0x73, 0x79, 0x6e,
	0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_warden_async_v1beta1_ve_proto_rawDescOnce sync.Once
	file_warden_async_v1beta1_ve_proto_rawDescData = file_warden_async_v1beta1_ve_proto_rawDesc
)

func file_warden_async_v1beta1_ve_proto_rawDescGZIP() []byte {
	file_warden_async_v1beta1_ve_proto_rawDescOnce.Do(func() {
		file_warden_async_v1beta1_ve_proto_rawDescData = protoimpl.X.CompressGZIP(file_warden_async_v1beta1_ve_proto_rawDescData)
	})
	return file_warden_async_v1beta1_ve_proto_rawDescData
}

var file_warden_async_v1beta1_ve_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_warden_async_v1beta1_ve_proto_goTypes = []interface{}{
	(*AsyncInjectedTx)(nil),        // 0: warden.async.v1beta1.AsyncInjectedTx
	(*AsyncVoteExtension)(nil),     // 1: warden.async.v1beta1.AsyncVoteExtension
	(*AsyncVoteExtensionItem)(nil), // 2: warden.async.v1beta1.AsyncVoteExtensionItem
	(*FutureResult)(nil),           // 3: warden.async.v1beta1.FutureResult
	(*abci.ExtendedVoteInfo)(nil),  // 4: tendermint.abci.ExtendedVoteInfo
	(FutureVoteType)(0),            // 5: warden.async.v1beta1.FutureVoteType
}
var file_warden_async_v1beta1_ve_proto_depIdxs = []int32{
	3, // 0: warden.async.v1beta1.AsyncInjectedTx.results:type_name -> warden.async.v1beta1.FutureResult
	4, // 1: warden.async.v1beta1.AsyncInjectedTx.extended_votes_info:type_name -> tendermint.abci.ExtendedVoteInfo
	2, // 2: warden.async.v1beta1.AsyncVoteExtension.votes:type_name -> warden.async.v1beta1.AsyncVoteExtensionItem
	5, // 3: warden.async.v1beta1.AsyncVoteExtensionItem.vote:type_name -> warden.async.v1beta1.FutureVoteType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_warden_async_v1beta1_ve_proto_init() }
func file_warden_async_v1beta1_ve_proto_init() {
	if File_warden_async_v1beta1_ve_proto != nil {
		return
	}
	file_warden_async_v1beta1_future_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_warden_async_v1beta1_ve_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncInjectedTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warden_async_v1beta1_ve_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncVoteExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_warden_async_v1beta1_ve_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncVoteExtensionItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_warden_async_v1beta1_ve_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warden_async_v1beta1_ve_proto_goTypes,
		DependencyIndexes: file_warden_async_v1beta1_ve_proto_depIdxs,
		MessageInfos:      file_warden_async_v1beta1_ve_proto_msgTypes,
	}.Build()
	File_warden_async_v1beta1_ve_proto = out.File
	file_warden_async_v1beta1_ve_proto_rawDesc = nil
	file_warden_async_v1beta1_ve_proto_goTypes = nil
	file_warden_async_v1beta1_ve_proto_depIdxs = nil
}
