---
name: Daily Scan Images

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  scan-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(vars.SCAN_IMAGES_LIST) }}
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest"
          format: "sarif"
          output: "trivy.sarif"
          severity: "CRITICAL,HIGH"
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy.sarif"
